// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleApi
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration of the service.
public struct ServiceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The DNS address at which this service is available.
  ///
  /// An example DNS address would be:
  /// `calendar.googleapis.com`.
  public var name: Swift.String = Swift.String()

  /// The product title for this service.
  public var title: Swift.String = Swift.String()

  /// A list of API interfaces exported by this service. Contains only the names,
  /// versions, and method names of the interfaces.
  public var apis: [GoogleWKT.Api] = []

  /// Additional API documentation. Contains only the summary and the
  /// documentation URL.
  public var documentation: GoogleApi.Documentation? = nil

  /// Quota configuration.
  public var quota: GoogleApi.Quota? = nil

  /// Auth configuration. Contains only the OAuth rules.
  public var authentication: GoogleApi.Authentication? = nil

  /// Configuration controlling usage of this service.
  public var usage: GoogleApi.Usage? = nil

  /// Configuration for network endpoints. Contains only the names and aliases
  /// of the endpoints.
  public var endpoints: [GoogleApi.Endpoint] = []

  /// Defines the monitored resources used by this service. This is required
  /// by the [Service.monitoring][google.api.Service.monitoring] and
  /// [Service.logging][google.api.Service.logging] configurations.
  public var monitoredResources: [GoogleApi.MonitoredResourceDescriptor] = []

  /// Monitoring configuration.
  /// This should not include the 'producer_destinations' field.
  public var monitoring: GoogleApi.Monitoring? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ServiceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ServiceConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let title = CodingKeys(stringValue: "title")
    static let apis = CodingKeys(stringValue: "apis")
    static let documentation = CodingKeys(stringValue: "documentation")
    static let quota = CodingKeys(stringValue: "quota")
    static let authentication = CodingKeys(stringValue: "authentication")
    static let usage = CodingKeys(stringValue: "usage")
    static let endpoints = CodingKeys(stringValue: "endpoints")
    static let monitoredResources = CodingKeys(stringValue: "monitoredResources")
    static let monitoring = CodingKeys(stringValue: "monitoring")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "title",
      "apis",
      "documentation",
      "quota",
      "authentication",
      "usage",
      "endpoints",
      "monitoredResources",
      "monitoring",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
      self.title = value
    }
    if let value = try container.decodeIfPresent([GoogleWKT.Api].self, forKey: .apis) {
      self.apis = value
    }
    self.documentation = try container.decodeIfPresent(
      GoogleApi.Documentation.self, forKey: .documentation)
    self.quota = try container.decodeIfPresent(GoogleApi.Quota.self, forKey: .quota)
    self.authentication = try container.decodeIfPresent(
      GoogleApi.Authentication.self, forKey: .authentication)
    self.usage = try container.decodeIfPresent(GoogleApi.Usage.self, forKey: .usage)
    if let value = try container.decodeIfPresent([GoogleApi.Endpoint].self, forKey: .endpoints) {
      self.endpoints = value
    }
    if let value = try container.decodeIfPresent(
      [GoogleApi.MonitoredResourceDescriptor].self, forKey: .monitoredResources)
    {
      self.monitoredResources = value
    }
    self.monitoring = try container.decodeIfPresent(GoogleApi.Monitoring.self, forKey: .monitoring)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.apis, forKey: .apis)
    try container.encodeIfPresent(self.documentation, forKey: .documentation)
    try container.encodeIfPresent(self.quota, forKey: .quota)
    try container.encodeIfPresent(self.authentication, forKey: .authentication)
    try container.encodeIfPresent(self.usage, forKey: .usage)
    try container.encode(self.endpoints, forKey: .endpoints)
    try container.encode(self.monitoredResources, forKey: .monitoredResources)
    try container.encodeIfPresent(self.monitoring, forKey: .monitoring)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.serviceusage.v1.ServiceConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
