// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class ServiceUsageRetry: ServiceUsageStub {
    let inner: any ServiceUsageStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ServiceUsageStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func enableService(
      request: EnableServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EnableServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.enableService(request: r, options: o)
        })
    }

    public func disableService(
      request: DisableServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DisableServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.disableService(request: r, options: o)
        })
    }

    public func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceusageV1.Service {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiServiceusageV1.Service
          in
          return try await self.inner.getService(request: r, options: o)
        })
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceusageV1.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiServiceusageV1.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func batchEnableServices(
      request: BatchEnableServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchEnableServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.batchEnableServices(request: r, options: o)
        })
    }

    public func batchGetServices(
      request: BatchGetServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceusageV1.BatchGetServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: BatchGetServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleApiServiceusageV1.BatchGetServicesResponse
          in
          return try await self.inner.batchGetServices(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
